"""Tests for TriggerManager and trigger-managing tools."""

import asyncio

import pytest

from kohakuterrarium.core.events import TriggerEvent
from kohakuterrarium.core.trigger_manager import TriggerManager, TriggerInfo
from kohakuterrarium.modules.trigger.base import BaseTrigger


class MockTrigger(BaseTrigger):
    """Trigger that fires once then blocks."""

    def __init__(self, event_content: str = "fired"):
        super().__init__()
        self._event_content = event_content
        self._fired = False
        self._block = asyncio.Event()

    async def wait_for_trigger(self) -> TriggerEvent | None:
        if not self._running:
            return None
        if self._fired:
            # Block until cancelled (like a real trigger waiting for next event)
            await self._block.wait()
            return None
        self._fired = True
        return TriggerEvent(type="test", content=self._event_content)


class TestTriggerManager:
    """Test TriggerManager lifecycle."""

    @pytest.fixture
    def events(self):
        return []

    @pytest.fixture
    def manager(self, events):
        async def process_event(event):
            events.append(event)

        return TriggerManager(process_event)

    async def test_add_and_list(self, manager):
        trigger = MockTrigger()
        tid = await manager.add(trigger, trigger_id="test_1")
        assert tid == "test_1"
        assert len(manager.list()) == 1
        info = manager.get("test_1")
        assert info is not None
        assert info.trigger_type == "MockTrigger"
        assert info.running is True
        await manager.stop_all()

    async def test_add_autogenerated_id(self, manager):
        trigger = MockTrigger()
        tid = await manager.add(trigger)
        assert tid.startswith("trigger_")
        assert manager.get(tid) is not None
        await manager.stop_all()

    async def test_add_duplicate_raises(self, manager):
        t1 = MockTrigger()
        await manager.add(t1, trigger_id="dup")
        t2 = MockTrigger()
        with pytest.raises(ValueError, match="already exists"):
            await manager.add(t2, trigger_id="dup")
        await manager.stop_all()

    async def test_remove(self, manager):
        trigger = MockTrigger()
        await manager.add(trigger, trigger_id="rem")
        assert await manager.remove("rem") is True
        assert manager.get("rem") is None
        assert not trigger.is_running

    async def test_remove_nonexistent(self, manager):
        assert await manager.remove("ghost") is False

    async def test_get_trigger_instance(self, manager):
        trigger = MockTrigger()
        await manager.add(trigger, trigger_id="inst")
        assert manager.get_trigger("inst") is trigger
        await manager.stop_all()

    async def test_stop_all(self, manager):
        t1 = MockTrigger()
        t2 = MockTrigger()
        await manager.add(t1, trigger_id="a")
        await manager.add(t2, trigger_id="b")
        assert len(manager.list()) == 2
        await manager.stop_all()
        assert len(manager.list()) == 0

    async def test_trigger_fires_process_event(self, manager, events):
        trigger = MockTrigger(event_content="hello")
        await manager.add(trigger, trigger_id="fire_test")
        await asyncio.sleep(0.2)
        await asyncio.wait_for(manager.stop_all(), timeout=2.0)
        assert len(events) >= 1
        assert events[0].content == "hello"

    async def test_add_without_autostart(self, manager):
        trigger = MockTrigger()
        tid = await manager.add(trigger, trigger_id="nostart", autostart=False)
        assert manager.get(tid) is not None
        assert not trigger.is_running
        await manager.start_all()
        assert trigger.is_running
        await manager.stop_all()

    async def test_set_context_all(self, manager):
        trigger = MockTrigger()
        await manager.add(trigger, trigger_id="ctx", autostart=False)
        manager.set_context_all({"key": "value"})
        assert trigger._context.get("key") == "value"


class TestListTriggersTool:
    """Test the list_triggers builtin tool."""

    async def test_no_triggers(self):
        from kohakuterrarium.builtins.tools.list_triggers import ListTriggersTool
        from kohakuterrarium.modules.tool.base import ToolContext

        tool = ListTriggersTool()

        # Mock agent with empty trigger_manager
        class MockAgent:
            trigger_manager = TriggerManager(lambda e: None)

        ctx = ToolContext(
            agent_name="test",
            session=None,
            working_dir=__import__("pathlib").Path("."),
            agent=MockAgent(),
        )
        result = await tool.execute({"content": ""}, context=ctx)
        assert "No active triggers" in result.output

    async def test_with_triggers(self):
        from kohakuterrarium.builtins.tools.list_triggers import ListTriggersTool
        from kohakuterrarium.modules.tool.base import ToolContext

        tool = ListTriggersTool()

        class MockAgent:
            trigger_manager = TriggerManager(lambda e: None)

        agent = MockAgent()
        t = MockTrigger()
        # Add without autostart to avoid event loop issues
        await agent.trigger_manager.add(t, trigger_id="test_obs", autostart=False)

        ctx = ToolContext(
            agent_name="test",
            session=None,
            working_dir=__import__("pathlib").Path("."),
            agent=agent,
        )
        result = await tool.execute({"content": ""}, context=ctx)
        assert "test_obs" in result.output
        assert "MockTrigger" in result.output
