"""Workspace Protocol.

Declares the shape every workspace implementation satisfies. The
local FS implementation lives in ``local.py`` (added in Phase 1),
a stub for remote mode will land in Phase 8.

Routes depend only on this Protocol via ``deps.get_workspace``,
so swapping the backing implementation is invisible to callers.
"""

from typing import Protocol, runtime_checkable


@runtime_checkable
class Workspace(Protocol):
    """Protocol for a studio workspace (FS, remote server, …)."""

    root: str  # display label (usually a path string)

    # Creatures ------------------------------------------------------
    def list_creatures(self) -> list[dict]: ...
    def load_creature(self, name: str) -> dict: ...
    def save_creature(self, name: str, data: dict) -> dict: ...
    def scaffold_creature(self, name: str, base: str | None) -> dict: ...
    def delete_creature(self, name: str) -> None: ...

    # Modules --------------------------------------------------------
    def list_modules(self, kind: str) -> list[dict]: ...
    def load_module(self, kind: str, name: str) -> dict: ...
    def save_module(self, kind: str, name: str, data: dict) -> dict: ...
    def scaffold_module(self, kind: str, name: str, template: str | None) -> dict: ...
    def delete_module(self, kind: str, name: str) -> None: ...

    # Prompts --------------------------------------------------------
    def read_prompt(self, creature: str, rel: str) -> str: ...
    def write_prompt(self, creature: str, rel: str, body: str) -> None: ...
